### ISSUE TITLE
Create a Test-Case

### ISSUE THREAD

**Issue by wagnermduarte** [junit-tools-team/junit-tools#3]
When i try to create a test-case, junit-tools bring me return error, like you can seen in print screen in attach file.
![error](https://user-images.githubusercontent.com/23167784/27715781-eb93a5c6-5d0f-11e7-911d-c6af8f206403.png)

**Comment by robertstreng** [comment]
Hallo,

to analyze and reproduce the error, I need further informations. 
Did you create the test-project manually or via junit-tools? Did you refresh your workspace and was that the first test-class you have tried to generate? Did the generation work for other projects and classes?

Regards
Robert

**Comment by wagnermduarte** [comment]
Hello,

Ok.

I created by junit-tools, thats the first time ia try to generate. i tryed
to refresh a maven build and thats ok too, but stil don't generate the test
cases.

Att,

Wagner Marcondes Duarte, CTAL-TA
Analista de Teste
Cel: +55 41 9597-6311

2017-06-30 10:58 GMT-03:00 Robert Streng <notifications@github.com>:

**Comment by robertstreng** [comment]
Ok, then you apparently do not have the latest version of junit-tools.
We deactivated the automatic creation of the test project because it was partly not working properly.
Please try to delete the created testproject, create it manually again and then try to generate the testclass again.

I tried it and it works. 
Created package, class and test-suite:
![pastedgraphic-4](https://user-images.githubusercontent.com/15949264/27747941-b9ee3fb8-5dcd-11e7-8d6d-1a39fd3a3945.png)

Generated output:
![pastedgraphic-3](https://user-images.githubusercontent.com/15949264/27747953-c356fd88-5dcd-11e7-9d5d-055b2a480c9a.png)

**Comment by wagnermduarte** [comment]
i've tried that and still don't work.
do you want try to see the problem by teamviewer?

Att,

Wagner Marcondes Duarte, CTAL-TA
Analista de Teste
Cel: +55 41 9597-6311

2017-06-30 14:53 GMT-03:00 Robert Streng <notifications@github.com>:

**Comment by robertstreng** [comment]
Yes, you can send your ID to support@junit-tools.org

**Comment by wagnermduarte** [comment]
i will,
before the log from error
Java Model Exception: Java Model Status [src [in supplier-delivery.test] is
not on its project's build path]
    at
org.eclipse.jdt.internal.core.JavaElement.newJavaModelException(JavaElement.java:566)
    at
org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:247)
    at
org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:505)
    at
org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:241)
    at
org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:505)
    at
org.eclipse.jdt.internal.core.CompilationUnit.openAncestors(CompilationUnit.java:1180)
    at
org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:241)
    at
org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:579)
    at
org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:316)
    at
org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:302)
    at org.eclipse.jdt.internal.core.Openable.getBuffer(Openable.java:285)
    at
org.eclipse.jdt.internal.core.CreateCompilationUnitOperation.getBuffer_aroundBody0(CreateCompilationUnitOperation.java:91)
    at
org.eclipse.jdt.internal.core.CreateCompilationUnitOperation.executeOperation(CreateCompilationUnitOperation.java:91)
    at
org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:724)
    at
org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
    at
org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
    at
org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:795)
    at
org.eclipse.jdt.internal.core.CompilationUnit.createType(CompilationUnit.java:457)
    at
org.junit.tools.generator.TestClassGenerator.createTestClassFrame(TestClassGenerator.java:559)
    at
org.junit.tools.generator.TestClassGenerator.createTestClassFrame(TestClassGenerator.java:455)
    at
org.junit.tools.generator.TestClassGenerator.generate(TestClassGenerator.java:108)
    at org.junit.tools.base.MainController$1.run(MainController.java:174)
    at
org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)

Java Model Exception: Java Model Status [src [in supplier-delivery.test] is
not on its project's build path]
    at
org.eclipse.jdt.internal.core.JavaElement.newJavaModelException(JavaElement.java:566)
    at
org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:247)
    at
org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:505)
    at
org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:241)
    at
org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:505)
    at
org.eclipse.jdt.internal.core.CompilationUnit.openAncestors(CompilationUnit.java:1180)
    at
org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:241)
    at
org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:579)
    at
org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:316)
    at
org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:302)
    at org.eclipse.jdt.internal.core.Openable.getBuffer(Openable.java:285)
    at
org.eclipse.jdt.internal.core.CreateCompilationUnitOperation.getBuffer_aroundBody0(CreateCompilationUnitOperation.java:91)
    at
org.eclipse.jdt.internal.core.CreateCompilationUnitOperation.executeOperation(CreateCompilationUnitOperation.java:91)
    at
org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:724)
    at
org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
    at
org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
    at
org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:795)
    at
org.eclipse.jdt.internal.core.CompilationUnit.createType(CompilationUnit.java:457)
    at
org.junit.tools.generator.TestClassGenerator.createTestClassFrame(TestClassGenerator.java:559)
    at
org.junit.tools.generator.TestClassGenerator.createTestClassFrame(TestClassGenerator.java:455)
    at
org.junit.tools.generator.TestClassGenerator.generate(TestClassGenerator.java:108)
    at org.junit.tools.base.MainController$1.run(MainController.java:174)
    at
org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)

  org.junit.tools.base.JUTException: Java Model Exception: Java Model
Status [src [in supplier-delivery.test] is not on its project's build path]
      at
org.eclipse.jdt.internal.core.JavaElement.newJavaModelException(JavaElement.java:566)
      at
org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:247)
      at
org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:505)
      at
org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:241)
      at
org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:505)
      at
org.eclipse.jdt.internal.core.CompilationUnit.openAncestors(CompilationUnit.java:1180)
      at
org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:241)
      at
org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:579)
      at
org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:316)
      at
org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:302)
      at org.eclipse.jdt.internal.core.Openable.getBuffer(Openable.java:285)
      at
org.eclipse.jdt.internal.core.CreateCompilationUnitOperation.getBuffer_aroundBody0(CreateCompilationUnitOperation.java:91)
      at
org.eclipse.jdt.internal.core.CreateCompilationUnitOperation.executeOperation(CreateCompilationUnitOperation.java:91)
      at
org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:724)
      at
org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
      at
org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
      at
org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:795)
      at
org.eclipse.jdt.internal.core.CompilationUnit.createType(CompilationUnit.java:457)
      at
org.junit.tools.generator.TestClassGenerator.createTestClassFrame(TestClassGenerator.java:559)
      at
org.junit.tools.generator.TestClassGenerator.createTestClassFrame(TestClassGenerator.java:455)
      at
org.junit.tools.generator.TestClassGenerator.generate(TestClassGenerator.java:108)
      at org.junit.tools.base.MainController$1.run(MainController.java:174)
      at
org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)

      at
org.junit.tools.base.MainController.generateTestclass(MainController.java:195)
      at
org.junit.tools.base.MainController.generateTestclass(MainController.java:85)
      at
org.junit.tools.handler.GenerateTestClassHandler.execute(GenerateTestClassHandler.java:43)
      at
org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:291)
      at
org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:92)
      at sun.reflect.GeneratedMethodAccessor159.invoke(Unknown Source)
      at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.lang.reflect.Method.invoke(Method.java:498)
      at
org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
      at
org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:305)
      at
org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:239)
      at
org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
      at
org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
      at
org.eclipse.core.commands.Command.executeWithChecks(Command.java:494)
      at
org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
      at
org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
      at
org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:431)
      at
org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:446)
      at
org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:472)
      at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
      at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5252)
      at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1348)
      at
org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4522)
      at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4107)
      at
org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
      at
org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
      at
org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1044)
      at
org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
      at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
      at
org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
      at
org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
      at
org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
      at
org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
      at
org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
      at
org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
      at
org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
      at
org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
      at
org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.lang.reflect.Method.invoke(Method.java:498)
      at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
      at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
      at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
      at org.eclipse.equinox.launcher.Main.main(Main.java:1472)


Att,

Wagner Marcondes Duarte, CTAL-TA
Analista de Teste
Cel: +55 41 9597-6311

2017-06-30 16:33 GMT-03:00 Robert Streng <notifications@github.com>:

**Comment by robertstreng** [comment]
We found the problem. The cause for the error is wrong settings in the test-project. This occurs, for example, if maven/lombok is used and the base project is copied and used as test-project. **To solve the problem, the test project must be created from scratch.**
We will commit a fix, so that in this case no hard error but a controlled message comes.

**Comment by robertstreng** [comment]
We have fixed the problem and released the new version (1.0.6). It's available on the eclipse marketplace / update-site. 

If a required folder is missing in the build path of the test project, it is now added automatically.
If it is a nested folder, an error appears with the corresponding note: E.g. when trying to add "src" if "src/java/main" already exists.
