### ISSUE TITLE
Integration of Easy mock with junit-tools

### ISSUE THREAD

**Issue by ayujain7** [junit-tools-team/junit-tools#5]
Is there a way to use EasyMock with the junit-tools?

**Comment by robertstreng** [comment]
It is not implemented yet, but you can contribute the generator:
http://www.junit-tools.org/index.php/documentation#extension-points

Or implement it directly and create a pull request. This would be great.

**Comment by robertstreng** [comment]
In the new version of JUnit-Tools (1.1.0) we use PowerMock (EasyMock / Mockito) as default to invoke a non-public method of an instance or class.

To add PowerMock to your projects see https://github.com/powermock/powermock/wiki/Getting-Started.
