### ISSUE TITLE
@MethodRef annotation not found

### ISSUE THREAD

**Issue by ssnyder** [junit-tools-team/junit-tools#6]
I just installed this plugin on Eclipse Oxygen 3a (4.7.3a) (it was previously installed with the same bug, so I uninstalled/reinstalled thinking it was a setup issue).

When I generate a test class, it cannot organize the imports error pops up - claims it needs human interaction.  When the file loads the @Generated and @MethodRef annotations are not found - so I have to import the javax.annotation for the @Generated  - but there are no suggestions for the @MethodRef.

Also Deencapsulate does not compile, nor does it have any suggestions.

I am using gradle for my build/deploy, is there a library I should be adding for the testCompile/testRuntime?  (Is this library available on one of the typical sites like jfrog? mavenCentral?) Something else?  I reviewed the docs online and the existing issues - and I didn't see anything about resolving this issue.

Sharon

**Comment by robertstreng** [comment]
Hello Sharon,

unfortunately the required lib is not available in a public gradle or maven repository.

You must manually add junit-tools.jar to your test-project-dependencies. You can download the jar file here: http://junit-tools.org/index.php/download.

Alternatively, you can create the required annotation yourself.

See also here for more informations:
http://junit-tools.org/index.php/getting-started, section „Test-Project-Dependencies“.

Kind regards
