### ISSUE TITLE
plans to upgrade to newer versions of jmockit?

### ISSUE THREAD

**Issue by ssnyder** [junit-tools-team/junit-tools#7]
Version 1.36 removed functionality (deprecated in 1.35) that is used by junit-tools:

> Deprecated the "invoke" and "newInstance" methods from the Deencapsulation class. These are simple Reflection-backed convenience methods, which are no longer useful in the overall context of JMockit APIs.

The current version is 1.43, and 1.21 is delivered in the .zip file needed for the jar dependencies....any plans to upgrade (and obviously to replace that Deencapsulation functionality)?

**Comment by robertstreng** [comment]
Unfortunately, there is no alternative to this functionality in JMockit.

We have released a new version (1.1.0) that uses PowerMock (EasyMock / Mockito) as default to invoke a non-public method of an instance or class.

For users who are still working with an old version of JMockit (up to version 1.34), there is the option to use the settings to select the mock framework (preferences / JUnit tools).

To add PowerMock to your projects see https://github.com/powermock/powermock/wiki/Getting-Started.
