### ISSUE TITLE
Unable to generate test class for web application

### ISSUE THREAD

**Issue by AjitGambhire** [junit-tools-team/junit-tools#8]
**Error as Below:**
Error While processing..!
Reason: 
 java model exception: java model status[src[in Test]is not on its project build path 
![JunitToolsissue](https://user-images.githubusercontent.com/54053122/62915648-dc569180-bdb2-11e9-9a14-a89caf0e1dd8.PNG)

**Comment by robertstreng** [comment]
The cause for the error is wrong settings in the test-project. This occurs, for example, if maven/lombok is used and the base project is copied and used as test-project. To solve the problem, the test project must be created from scratch. See also #3.

**Comment by AjitGambhire** [comment]
can you please provide the link of eclipse marketplace update site?

**Comment by AjitGambhire** [comment]
thanks....
